<p>Üdvözöljük <?=$name;?>!</p>

<p>Ezt az e-mailt azért kapta, mert az oldalunkon korábban regisztrált. Adatvédelmi tájékoztatónknak megfelelően dönthet úgy, hogy a soron következő részvételi költségvetés ciklusban is ezt a fiókot használja.</p>

<p>Ha nem szeretné megtartani a fiókját, nincs más dolga. A fiók 48 órán belül törlődni fog.</p>

<p>Fiókja megőrzéséhez és aktíválásához kattintson <a href="<?=$activation;?>" target="_blank" rel="noopener">erre a linkre</a>.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
