<p>Üdvözlünk <?=$name;?>!</p>

<p>Ezt az e-mailt azért kaptad, mert az oldalunkon korábban regisztráltál. Adatvédelmi tájékoztatónknak megfelelően dönthetsz úgy, hogy a soron következő közösségi költségvetési ciklusban is ezt a fiókot használod.</p>

<p>Ha nem szeretnéd megtartani a fiókodat, nincs más dolgod. A fiók 48 órán belül törlődni fog.</p>

<p>Fiókod megőrzéséhez és aktíválásához kattints <a href="<?=$activation;?>" target="_blank" rel="noopener">erre a linkre</a>.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
