<p>Üdvözlünk <?=$name;?>!</p>

<p>Ezt az e-mailt azért kaptad, mert a Fővárosi Önkormányzat otlet.budapest.hu oldalán korábban regisztráltál.<br />November elején elindul a fővárosi részvételi költségvetés - új nevén közösségi költségvetés - második éve. Adatvédelmi tájékoztatónknak megfelelően dönthetsz úgy, hogy a soron következő közösségi költségvetési ciklusban is ezt a fiókot használod.</p>

<p>Tájékoztatunk, hogy a jövőben ötletbeadás esetén a regisztrációkor megadott vezeték- és utónevet fogjuk feltüntetni az oldalon (ez esetedben: <?=$lastname;?> <?=$firstname;?>).</p>

<p>Ha nem szeretnéd megtartani a fiókodat, nincs más dolgod. Az eredeti fiókod e-mailünk kiküldését követően, 120 óra elteltével automatikusan törlődni fog.</p>

<p>Fiókod megőrzéséhez és aktiválásához kattints <a href="<?=$activation;?>" target="_blank" rel="noopener">erre a linkre</a>.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
