<p>Üdvözlünk <?=$name;?>!</p>

<p>Sikeresen fogadtuk a fővárosi közösségi költségvetésen beküldött ötletedet. Feldolgozás után – amennyiben megfelel a formai követelményeknek – közzétesszük az <a href="https://otlet.budapest.hu">otlet.budapest.hu</a> oldalon.</p>

<p><b>Ötlet megnevezése:</b><br>
<?=$idea['title'];?></p>


<p><b>Mire megoldás az ötleted?</b><br>
<?=$idea['solution'];?></p>


<p><b>Az ötlet leírása:</b><br>
<?=$idea['description'];?></p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
