<p>Üdvözöljük <?=$name;?>!</p>

<p>Köszönjük a fővárosi részvételi költségvetésen leadott szavazatát! A szavazás népszerűsítésére nyereményjátékot indítottunk, amire Önnek is lehetősége van jelentkezni:</p>

<p>a BKV Zrt. jóvoltából a szavazók közül véletlenszerűen 20 fő betekintést nyerhet az 50-es években - a 2-es metróval egyidőben - kiépített, sokáig titokban tartott, a köznyelvben Rákosi-bunkerként ismert atombiztos óvóhelybe.</p>

<p>A nyereményjátékon való részvételhez kérjük – legkésőbb <b>2021. augusztus 12-ig</b> – kattintson az alábbi linkre.</p>

<p><a href="<?=$prizeActivation;?>" target="_blank" rel="noopener">Jelentkezem a nyereményjátékra</a></p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
