<p>Kedves <?=$name;?>!</p>

<p>Ezt az e-mailt azért kaptad, mert az oldalunkon a jelszó visszaállítás funkciót használták. Amennyiben nem Te voltál, töröld a levelet, nincs más teendőd.</p>

<p>Amennyiben Te kérted a jelszó visszaállítását, a <a href="<?=$forgotLink;?>" target="_blank" rel="noopener">linkre kattinva</a> megváltoztathatod.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
