<p>Üdvözöljük <?=$name;?>!</p>

<p>Ezt az e-mailt azért kapta, mert a fővárosi részvételi költségvetés oldalán a felhasználónév emlékeztetőre kattintott.</p>

<p>A felhasználó neve:<br /><?=$username;?></p>

<p>Bejelentkezhet a <a href="https://otlet.budapest.hu/szavazas/bejelentkezes" target="_blank" rel="noopener">következő linken</a>.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
