<p>Üdvözöljük <?=$name;?>!</p>

<p>Múlt héten emailben értesítettük, hogy a részvételi költségvetés népszerűsítéséhez nyereményjátékot indítunk, amelyen Ön is részt vehet. Amiről nem írtunk, de lényeges információ, hogy mit lehet nyerni a nyereményjátékon:</p>

<p>a BKV Zrt. jóvoltából a szavazók közül véletlenszerűen 20 fő betekintést nyerhet az 50-es években - a 2-es metróval egyidőben - kiépített, sokáig titokban tartott, a köznyelvben Rákosi-bunkerként ismert atombiztos óvóhelybe.</p>

<p>A nyereményjátékon való részvételhez kérjük kattintson az alábbi, egyszerhasználatos linkre, ha még nem tette. Amennyiben már jelentkezett, nincs teendője.</p>

<p><a href="<?=$prizeActivation;?>" target="_blank" rel="noopener">Jelentkezem a nyereményjátékra</a></p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
