<p>Kedves <?=$name;?>!</p>

<p>Sikeresen leadtad szavazatodat a fővárosi részvételi költségvetés oldalán. Az alábbi projektekre szavaztál:</p>

<p>Zöld Budapest: <b><?=$votes['GREEN']['title'];?></b></p>
<p>Esélyteremtő Budapest: <b><?=$votes['CARE']['title'];?></b></p>
<p>Nyitott Budapest: <b><?=$votes['WHOLE']['title'];?></b></p>

<p>Köszönjük, hogy aktívan részt veszel Budapest fejlesztésében, és éltél szavazati jogoddal a fővárosi közösségi költségvetés második évében!<br />Kérjük, bíztasd ismerőseidet is, hogy szavazzanak a legjobb ötletekre.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
