<p>Kedves Ötletgazda!</p>

<p>Köszönjük, hogy javaslatot tettél arra, mit valósítson meg a Fővárosi Önkormányzat a közösségi költségvetés egymilliárd forintos keretéből!</p>

<p><b><?=$ideaTitle;?></b> nevű ötletedet közzétettük az otlet.budapest.hu oldalon a beküldött ötletek menüpontban.</p>

<p><?=$ideaModText;?></p>

<p>Ötletedet az otlet.budapest.hu honlap jobb felső sarkában (Fiók) a Beküldött ötletek menüpont alatt is megtalálod.</p>

<p>Ötleted linkje: <a href="<?=$ideaLink;?>" rel="noopener noreferrer" target="_blank"><?=$ideaLink;?></a><br />
Ötleted azonosítószáma: <?=$ideaId;?><br />
Kérjük, jegyezd fel ezt az azonosítót, mert ennek segítségével fogod tudni nyomon követni az ötlet fejleményeit. Javasoljuk, hogy kísérd figyelemmel a folyamatot!</p>

<p>A budapestiek 2022. nyarán választják ki szavazással a legnépszerűbb, megvalósítandó ötleteket. Szavazólistára azon ötletek kerülnek, amelyek megkapták a Fővárosi Önkormányzat és szükség esetén az érintett kerület szakmai jóváhagyását, és a közösségi költségvetési tanács is támogatta őket. Reméljük, a te ötleted is ott lesz a szavazólistán.</p>

<p><i><b>Maradj velünk kapcsolatban, és értesülj a közösségi költségvetés legfrissebb híreiről, önkéntességi lehetőségeiről zárt Facebook csoportunkban: <a href="https://www.facebook.com/groups/2846239175600878" rel="noopener noreferrer" target="_blank">Nyitott Budapest Önkéntesek</a></b></i></p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
