Üdvözlünk <?=$name;?>!

Ezt az e-mailt azért kaptad, mert az oldalunkon korábban regisztráltál.
Adatvédelmi tájékoztatónknak megfelelően dönthetsz úgy, hogy a soron következő
közösségi költségvetési ciklusban is ezt a fiókot használod. Tájékoztatunk,
hogy a jövőben a regisztrációkor megadott vezeték-, és utónevet fogjuk
feltűntetni az oldalon.

Ha nem szeretnéd megtartani a fiókodat, nincs más dolgod. A fiók 48 órán
belül törlődni fog.

Fiókod megőrzéséhez és aktíválásához kattints erre a linkre.
<?=$activation;?>


Üdvözlettel:
<?=$infoMunicipality;?>

