Üdvözlünk <?=$name;?>!

Ezt az e-mailt azért kaptad, mert a Fővárosi Önkormányzat otlet.budapest.hu
oldalán korábban regisztráltál.
November elején elindul a fővárosi részvételi költségvetés - új nevén
közösségi költségvetés - második éve. Adatvédelmi tájékoztatónknak megfelelően
dönthetsz úgy, hogy a soron következő közösségi költségvetési ciklusban is
ezt a fiókot használod.

Tájékoztatunk, hogy a jövőben ötletbeadás esetén a regisztrációkor megadott
vezeték- és utónevet fogjuk feltüntetni az oldalon
(ez esetedben: <?=$lastname;?> <?=$firstname;?>).

Ha nem szeretnéd megtartani a fiókodat, nincs más dolgod. Az eredeti fiókod
e-mailünk kiküldését követően, 120 óra elteltével automatikusan törlődni fog.

Fiókod megőrzéséhez és aktiválásához kattints erre a linkre:
<?=$activation;?>


Üdvözlettel:
<?=$infoMunicipality;?>

