Üdvözöljük <?=$name;?>!

Múlt héten emailben értesítettük, hogy a részvételi költségvetés
népszerűsítéséhez nyereményjátékot indítunk, amelyen Ön is részt vehet. Amiről
nem írtunk, de lényeges információ, hogy mit lehet nyerni a nyereményjátékon:

a BKV Zrt. jóvoltából a szavazók közül véletlenszerűen 20 fő betekintést
nyerhet az 50-es években - a 2-es metróval egyidőben - kiépített, sokáig
titokban tartott, a köznyelvben Rákosi-bunkerként ismert atombiztos óvóhelybe.

A nyereményjátékon való részvételhez kérjük kattintson az alábbi,
egyszerhasználatos linkre, ha még nem tette. Amennyiben már jelentkezett,
nincs teendője.

Jelentkezem a nyereményjátékra
<?=$prizeActivation;?>


Üdvözlettel:
<?=$infoMunicipality;?>
