Üdvözöljük <?=$name;?>!

Ezt az e-mailt azért kapta, mert a fővárosi részvételi költségvetés oldalán
korábban regisztrált.

A részvételi költségvetés népszerűsítéséhez nyereményjátékot indítunk, amelyen
Ön is részt vehet. Ehhez nem kell más tennie, csak az alábbi linkre kattintva
jelentkezni.

Jelentkezem a nyereményjátékra
<?=$prizeActivation;?>


További információkért látogasson el az https://otlet.budapest.hu oldalra.


Üdvözlettel:
<?=$infoMunicipality;?>

