Üdvözöljük <?=$name;?>!

Köszönjük a fővárosi részvételi költségvetésen leadott szavazatát! A szavazás
népszerűsítésére nyereményjátékot indítottunk, amire Önnek is lehetősége van
jelentkezni:

a BKV Zrt. jóvoltából a szavazók közül véletlenszerűen 20 fő betekintést
nyerhet az 50-es években - a 2-es metróval egyidőben - kiépített, sokáig
titokban tartott, a köznyelvben Rákosi-bunkerként ismert atombiztos óvóhelybe.

A nyereményjátékon való részvételhez kérjük – legkésőbb 2021. augusztus 12-ig
– kattintson az alábbi linkre.

Jelentkezem a nyereményjátékra
<?=$prizeActivation;?>


Üdvözlettel:
<?=$infoMunicipality;?>
