Kedves <?=$name;?>!

Sikeresen leadta szavazatát a fővárosi részvételi költségvetés oldalán. Ön az
alábbi projektekre szavazott:

Zöld Budapest:
<?=$votes['GREEN']['title'];?>


Gondoskodó Budapest:
<?=$votes['CARE']['title'];?>


Egész Budapest:
<?=$votes['WHOLE']['title'];?>


Köszönjük, hogy aktívan részt vesz Budapest fejlesztésében, és élt szavazati
jogával a fővárosi részvételi költségvetés első évében!
Kérjük, bíztassa ismerőseit is, hogy szavazzanak a legjobb ötletekre.


Üdvözlettel:
<?=$infoMunicipality;?>

