Kedves <?=$name;?>!

Sikeresen leadtad szavazatodat a fővárosi közösségi költségvetés oldalán. Az
alábbi projektekre szavaztál:

Zöld Budapest:
<?=$votes['GREEN']['title'];?>


Esélyteremtő Budapest:
<?=$votes['CARE']['title'];?>


Nyitott Budapest:
<?=$votes['WHOLE']['title'];?>


Köszönjük, hogy aktívan részt veszel Budapest fejlesztésében és éltél
szavazati jogoddal a fővárosi közösségi költségvetés második évében! Kérjük,
biztasd ismerőseidet is, hogy szavazzanak a legjobb ötletekre!


Üdvözlettel:
<?=$infoMunicipality;?>

