Kedves Ötletgazda!

Köszönjük, hogy javaslatot tettél arra, mit valósítson meg a
Fővárosi Önkormányzat a közösségi költségvetés egymilliárd forintos keretéből!

<?=$ideaTitle;?> nevű ötletedet közzétettük az otlet.budapest.hu oldalon a
beküldött ötletek menüpontban.

Ötletedet az otlet.budapest.hu honlap jobb felső sarkában (Fiók) a Beküldött
ötletek menüpont alatt is megtalálod.

Ötleted linkje:
<?=$ideaLink;?>


Ötleted azonosítószáma:
<?=$ideaId;?>


Kérjük, jegyezd fel ezt az azonosítót, mert ennek segítségével fogod tudni
nyomon követni az ötlet fejleményeit. Javasoljuk, hogy kísérd figyelemmel a
folyamatot!

A budapestiek 2022. nyarán választják ki szavazással a legnépszerűbb,
megvalósítandó ötleteket. Szavazólistára azon ötletek kerülnek, amelyek
megkapták a Fővárosi Önkormányzat és szükség esetén az érintett kerület
szakmai jóváhagyását, és a közösségi költségvetési tanács is támogatta őket.
Reméljük, a te ötleted is ott lesz a szavazólistán.

Maradj velünk kapcsolatban, és értesülj a közösségi költségvetés legfrissebb
híreiről, önkéntességi lehetőségeiről zárt Facebook csoportunkban:

Nyitott Budapest Önkéntesek
https://www.facebook.com/groups/2846239175600878

Üdvözlettel:
<?=$infoMunicipality;?>
