<p>Üdvözöljük <?=$name;?>!</p>

<p>Ezt az e-mailt azért kapta, mert a fővárosi részvételi költségvetés oldalán korábban regisztrált.</p>

<p>Szeretnénk Önt arról tájékoztatni, hogy lehetőség van nyerményjátékunkra jelentkezni. Ehhez nem kell más tennie, csak az alábbi linkre kattintva jelentkezni.</p>

<p><a href="<?=$prizeActivation;?>" target="_blank" rel="noopener">Jelentkezem a nyereményjátékra</a></p>

<p>További információkért látogasson el az <a href="https://otlet.budapest.hu" target="_blank" rel="noopener">otlet.budapest.hu</a> oldalra.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
