<p>Kedves <?=$name;?>!</p>

<p>Ezt az e-mailt azért kapta, mert az oldalunkon a jelszó visszaállítás funkciót használták, amennyiben nem Ön volt, törölje a levelet, nincs más teendője.</p>

<p>Amennyiben Ön kérte a jelszó visszaállítását a <a href="<?=$forgotLink;?>" target="_blank" rel="noopener">linkre kattinva</a> megváltoztathatja.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
