<p>Üdvözöljük <?=$name;?>!</p>

<p>Ezt az e-mailt azért kapta, mert az <a href="https://otlet.budapest.hu" target="_blank" rel="noopener">Ötlet.budapest.hu</a>-n lévő fiókjához jelszó emlékeztetőt kértek, amennyiben nem Ön volt, törölje a levelet, nincs más teendője.</p>

<p>Amennyiben Ön kérte a jelszó emlékeztetőt a <a href="<?=$forgotLink;?>" target="_blank" rel="noopener">linkre kattinva</a> megváltoztathatja.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
