<p>Kedves <?=$name;?>!</p>

<p>Sikeresen leadta szavazatát a fővárosi részvételi költségvetésben az <a href="https://otlet.budapest.hu" target="_blank" rel="noopener">Ötlet.budapest.hu</a>-n. Ön az alábbi projektekre szavazott:</p>

<p>Zöld Budapest: <b><?=$votes['GREEN']['title'];?></b></p>
<p>Gondoskodó Budapest: <b><?=$votes['CARE']['title'];?></b></p>
<p>Egész Budapest: <b><?=$votes['WHOLE']['title'];?></b></p>

<p>Köszönjük, hogy aktívan részt vesz Budapest fejlesztésében, és élt szavazati jogával a fővárosi részvételi költségvetés első évében!<br />Kérjük, bíztassa ismerőseit is, hogy szavazzanak a legjobb ötletekre.</p>

<p>
    Üdvözlettel:<br />
    <?=$infoMunicipality;?>
</p>
